
services:
  postgres:
    image: postgres:15-alpine
    container_name: project_up_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: project_up_server
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CALLBACK_URL: ${GITHUB_CALLBACK_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      # Add OAuth client IDs and secrets after creating them
      # Add SMTP env vars for production here
    depends_on:
      - postgres
    restart: unless-stopped

  client:
    build: ./client
    container_name: project_up_client
    ports:
      - "8081:80" # Maps localhost:8081 to container:80
    depends_on:
      - server
    restart: unless-stopped

volumes:
  postgres_data:
